"""Parity tests: csdid (Python) vs R `did` v2.5.0.

Reference values in ``r_ref/ref_attgt.csv`` and ``r_ref/ref_aggte.csv`` are
generated by ``r_ref/generate_reference.R`` against the R `did` package
(v2.5.0). These tests confirm csdid reproduces R's ATT(g,t) point estimates and
analytical (bstrap=FALSE) standard errors, plus the four aggregation types.

If the reference CSVs are absent (no R available), the tests skip.
"""
import os
import warnings

import numpy as np
import pandas as pd
import pytest

from csdid.att_gt import ATTgt

REF_DIR = os.path.join(os.path.dirname(__file__), "r_ref")
DATA_DIR = os.path.dirname(__file__)

# scenario -> csdid parameters (must mirror r_ref/generate_reference.R)
SCENARIOS = {
    "mpdta_nev_dr": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~1", control_group="nevertreated",
        est_method="dr",
    ),
    "mpdta_nyt_dr": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~1", control_group="notyettreated",
        est_method="dr",
    ),
    "mpdta_nev_reg_cov": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~lpop", control_group="nevertreated",
        est_method="reg",
    ),
    "mpdta_nev_ipw": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~1", control_group="nevertreated",
        est_method="ipw",
    ),
    "sim_nev_dr": dict(
        data="sim_data.csv", yname="Y", tname="period", idname="id",
        gname="G", xformla="Y~X", control_group="nevertreated", est_method="dr",
    ),
}

# Tolerances: ATT point estimates match R to ~machine precision; analytical SEs
# match within a fraction of a percent. Allowances below are deliberately loose
# to stay robust across estimators (dr/reg/ipw).
ATT_ATOL = 1e-4
SE_RTOL = 0.03
SE_ATOL = 5e-4


def _has_ref():
    return (os.path.isfile(os.path.join(REF_DIR, "ref_attgt.csv"))
            and os.path.isfile(os.path.join(REF_DIR, "ref_aggte.csv")))


pytestmark = pytest.mark.skipif(
    not _has_ref(), reason="R `did` reference CSVs not generated (no R available)"
)


def _fit(scn):
    p = SCENARIOS[scn]
    data = pd.read_csv(os.path.join(DATA_DIR, p["data"]))
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = ATTgt(
            yname=p["yname"], tname=p["tname"], idname=p["idname"],
            gname=p["gname"], data=data, xformla=p["xformla"],
            control_group=p["control_group"],
        ).fit(est_method=p["est_method"], bstrap=False)
    return res


@pytest.fixture(scope="module")
def ref_attgt():
    return pd.read_csv(os.path.join(REF_DIR, "ref_attgt.csv"))


@pytest.fixture(scope="module")
def ref_aggte():
    return pd.read_csv(os.path.join(REF_DIR, "ref_aggte.csv"))


@pytest.mark.parametrize("scn", list(SCENARIOS))
def test_attgt_matches_r(scn, ref_attgt):
    """ATT(g,t) point estimates and analytical SEs match R `did`."""
    ref = ref_attgt[ref_attgt["scenario"] == scn]
    assert len(ref) > 0, f"no reference rows for {scn}"
    rkey = {(int(r.group), int(r.t)): (float(r.att), float(r.se))
            for _, r in ref.iterrows()}

    res = _fit(scn)
    g = np.asarray(res.MP["group"], dtype=float)
    t = np.asarray(res.MP["t"], dtype=float)
    att = np.asarray(res.results["att"], dtype=float)
    se = np.asarray(res.results["se"], dtype=float)

    n_checked = 0
    for gi, ti, ai, si in zip(g, t, att, se):
        ra, rs = rkey[(int(gi), int(ti))]
        np.testing.assert_allclose(
            ai, ra, atol=ATT_ATOL,
            err_msg=f"{scn}: ATT g={int(gi)} t={int(ti)} py={ai} r={ra}")
        if np.isfinite(si) and np.isfinite(rs):
            np.testing.assert_allclose(
                si, rs, rtol=SE_RTOL, atol=SE_ATOL,
                err_msg=f"{scn}: SE g={int(gi)} t={int(ti)} py={si} r={rs}")
        n_checked += 1
    assert n_checked == len(rkey), f"{scn}: checked {n_checked} of {len(rkey)}"


@pytest.mark.parametrize("scn", list(SCENARIOS))
def test_aggte_overall_matches_r(scn, ref_aggte):
    """Aggregated overall ATT and SE match R `did` for all four types."""
    ref = ref_aggte[ref_aggte["scenario"] == scn]
    for tp in ["simple", "group", "dynamic", "calendar"]:
        rrow = ref[ref["type"] == tp].iloc[0]
        res = _fit(scn)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res.aggte(typec=tp, bstrap=False)
        py_att = float(np.ravel(res.atte["overall_att"])[0])
        py_se = float(np.ravel(res.atte["overall_se"])[0])
        np.testing.assert_allclose(
            py_att, float(rrow["overall_att"]), atol=ATT_ATOL,
            err_msg=f"{scn}/{tp}: overall_att py={py_att} r={rrow['overall_att']}")
        np.testing.assert_allclose(
            py_se, float(rrow["overall_se"]), rtol=SE_RTOL, atol=SE_ATOL,
            err_msg=f"{scn}/{tp}: overall_se py={py_se} r={rrow['overall_se']}")


@pytest.mark.parametrize("scn", list(SCENARIOS))
@pytest.mark.parametrize("tp", ["group", "dynamic", "calendar"])
def test_aggte_egt_matches_r(scn, tp, ref_aggte):
    """Per-event/group/calendar ATT(egt) and SE match R `did`."""
    ref = ref_aggte[(ref_aggte["scenario"] == scn) & (ref_aggte["type"] == tp)]
    ref = ref[ref["egt"].notna()]
    rkey = {float(r.egt): (float(r.att_egt), float(r.se_egt))
            for _, r in ref.iterrows()}

    res = _fit(scn)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res.aggte(typec=tp, bstrap=False)
    egt = np.asarray(res.atte["egt"], dtype=float)
    att_egt = np.asarray(res.atte["att_egt"], dtype=float)
    se_egt = np.asarray(res.atte["se_egt"], dtype=float)

    for e, a, s in zip(egt, att_egt, se_egt):
        if float(e) not in rkey:
            continue
        ra, rs = rkey[float(e)]
        np.testing.assert_allclose(
            a, ra, atol=ATT_ATOL,
            err_msg=f"{scn}/{tp}: att_egt e={e} py={a} r={ra}")
        if np.isfinite(s) and np.isfinite(rs):
            np.testing.assert_allclose(
                s, rs, rtol=SE_RTOL, atol=SE_ATOL,
                err_msg=f"{scn}/{tp}: se_egt e={e} py={s} r={rs}")


# ─────────────────────────────────────────────────────────────
# fix_weights parity (time-varying weights) vs R `did` 2.5.0
# ─────────────────────────────────────────────────────────────

FIXWEIGHTS_REF = os.path.join(REF_DIR, "ref_fixweights.csv")
TVW_DATA = os.path.join(REF_DIR, "mpdta_tvw.csv")
_FW_TAGS = {"none": None, "base_period": "base_period",
            "first_period": "first_period", "varying": "varying"}


@pytest.mark.skipif(
    not (os.path.isfile(FIXWEIGHTS_REF) and os.path.isfile(TVW_DATA)),
    reason="fix_weights R reference not generated",
)
@pytest.mark.parametrize("tag", list(_FW_TAGS))
def test_fix_weights_matches_r(tag):
    """ATT(g,t) under each fix_weights mode matches R `did` (time-varying weights)."""
    ref = pd.read_csv(FIXWEIGHTS_REF)
    ref = ref[ref["fix_weights"] == tag]
    rkey = {(int(r.group), int(r.t)): float(r.att) for _, r in ref.iterrows()}
    data = pd.read_csv(TVW_DATA)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = ATTgt(
            yname="lemp", tname="year", idname="countyreal", gname="first.treat",
            data=data, control_group="nevertreated", xformla="lemp~1",
            weights_name="wt", fix_weights=_FW_TAGS[tag],
        ).fit(est_method="reg", bstrap=False)

    g = np.asarray(res.MP["group"], dtype=float)
    t = np.asarray(res.MP["t"], dtype=float)
    att = np.asarray(res.results["att"], dtype=float)
    for gi, ti, a in zip(g, t, att):
        np.testing.assert_allclose(
            a, rkey[(int(gi), int(ti))], atol=1e-6,
            err_msg=f"fix_weights={tag}: ATT g={int(gi)} t={int(ti)}")


# ─────────────────────────────────────────────────────────────
# Factor (categorical) covariate parity vs R `did` 2.5.0
# ─────────────────────────────────────────────────────────────

FACTOR_DIR = os.path.join(REF_DIR, "sim")
FACTOR_REF = os.path.join(FACTOR_DIR, "ref_factor.csv")
FACTOR_DATA = os.path.join(FACTOR_DIR, "factor_cov.csv")


@pytest.mark.skipif(
    not (os.path.isfile(FACTOR_REF) and os.path.isfile(FACTOR_DATA)),
    reason="factor-covariate R reference not generated",
)
@pytest.mark.parametrize("faster_mode", [False, True])
def test_factor_covariate_matches_r(faster_mode):
    """A categorical covariate (`Y~C(cat)`) matches R `did`'s `~factor(cat)`."""
    ref = pd.read_csv(FACTOR_REF)
    rkey = {(int(r.group), int(r.t)): (float(r.att), float(r.se)) for _, r in ref.iterrows()}
    data = pd.read_csv(FACTOR_DATA)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = ATTgt(yname="Y", tname="period", idname="id", gname="G", data=data,
                    control_group="nevertreated", xformla="Y~C(cat)",
                    faster_mode=faster_mode).fit("reg", bstrap=False)
    g = np.asarray(res.MP["group"], dtype=float)
    t = np.asarray(res.MP["t"], dtype=float)
    att = np.asarray(res.results["att"], dtype=float)
    se = np.asarray(res.results["se"], dtype=float)
    for gi, ti, a, s in zip(g, t, att, se):
        ra, rs = rkey[(int(gi), int(ti))]
        np.testing.assert_allclose(a, ra, atol=1e-6,
            err_msg=f"factor ATT g={int(gi)} t={int(ti)}")
        if np.isfinite(s) and np.isfinite(rs):
            np.testing.assert_allclose(s, rs, rtol=0.03, atol=5e-4,
                err_msg=f"factor SE g={int(gi)} t={int(ti)}")


# ─────────────────────────────────────────────────────────────
# Previously-unverified scenarios vs R `did` 2.5.0:
# repeated cross sections, universal base period, anticipation,
# weighted, and clustered (analytical) SE.
# ─────────────────────────────────────────────────────────────

GAPS_REF = os.path.join(REF_DIR, "sim", "ref_gaps.csv")
GAPS_DATA = os.path.join(REF_DIR, "sim", "mpdta_extra.csv")

# scenario -> (constructor kwargs, fit kwargs)
GAP_SCENARIOS = {
    "rc":            (dict(panel=False), dict(base_period="varying")),
    "universal":     (dict(), dict(base_period="universal")),
    "anticipation1": (dict(anticipation=1), dict(base_period="varying")),
    "weighted":      (dict(weights_name="wt"), dict(base_period="varying")),
    "clustered":     (dict(clustervar="clust"), dict(base_period="varying")),
}


@pytest.mark.skipif(
    not (os.path.isfile(GAPS_REF) and os.path.isfile(GAPS_DATA)),
    reason="gap-scenario R reference not generated",
)
@pytest.mark.parametrize("scn", list(GAP_SCENARIOS))
def test_gap_scenarios_match_r(scn):
    """RC / universal / anticipation / weighted / clustered-SE match R `did`."""
    ref = pd.read_csv(GAPS_REF)
    ref = ref[ref["scenario"] == scn]
    rkey = {(int(r.group), int(r.t)): (float(r.att), float(r.se)) for _, r in ref.iterrows()}
    data = pd.read_csv(GAPS_DATA)
    ikw, fkw = GAP_SCENARIOS[scn]
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = ATTgt(yname="lemp", tname="year", idname="countyreal", gname="first.treat",
                    data=data, control_group="nevertreated", **ikw).fit(
                        est_method="reg", bstrap=False, **fkw)
    g = np.asarray(res.MP["group"], dtype=float)
    t = np.asarray(res.MP["t"], dtype=float)
    att = np.asarray(res.results["att"], dtype=float)
    se = np.asarray(res.results["se"], dtype=float)
    n_checked = 0
    for gi, ti, a, s in zip(g, t, att, se):
        key = (int(gi), int(ti))
        if key not in rkey:
            continue
        ra, rs = rkey[key]
        np.testing.assert_allclose(a, ra, atol=1e-6, err_msg=f"{scn} ATT g={key[0]} t={key[1]}")
        if np.isfinite(s) and np.isfinite(rs):
            np.testing.assert_allclose(s, rs, rtol=0.03, atol=5e-4,
                err_msg=f"{scn} SE g={key[0]} t={key[1]}")
        n_checked += 1
    assert n_checked == len(rkey)



