"""Parity tests on SIMULATED data: csdid (Python) vs R `did` v2.5.0.

The behavioral suite validates many tests against the known simulated effect
(`att ≈ te`). This module proves that, on the *same* simulated datasets, csdid
reproduces R `did` to machine precision — so those ground-truth checks are
backed by exact R agreement, not just a loose tolerance.

Datasets live in ``r_ref/sim/<name>.csv`` (generated by ``helpers.build_sim_data``
and saved so R and Python consume identical inputs). R references are in
``r_ref/sim/ref_sim.csv`` (from ``r_ref/generate_sim_reference.R``).

Skips automatically if the reference is absent (no R available).
"""
import os
import warnings

import numpy as np
import pandas as pd
import pytest

from csdid.att_gt import ATTgt

SIM_DIR = os.path.join(os.path.dirname(__file__), "r_ref", "sim")
REF = os.path.join(SIM_DIR, "ref_sim.csv")

pytestmark = pytest.mark.skipif(
    not os.path.isfile(REF), reason="R sim reference not generated (no R available)"
)

# dr uses an iterative optimizer in DRDID, so allow a slightly looser ATT atol
# than reg (which is closed-form and matches R to ~1e-15).
ATT_ATOL = 1e-6
SE_RTOL = 0.05
SE_ATOL = 1e-3


def _scenarios():
    if not os.path.isfile(REF):
        return []
    ref = pd.read_csv(REF)
    return sorted(ref[["dataset", "control", "est"]].drop_duplicates()
                  .itertuples(index=False, name=None))


@pytest.fixture(scope="module")
def ref_sim():
    return pd.read_csv(REF)


@pytest.mark.parametrize("dataset,control,est", _scenarios())
def test_sim_attgt_matches_r(dataset, control, est, ref_sim):
    """ATT(g,t) and analytical SE on simulated data match R `did`."""
    grp = ref_sim[(ref_sim["dataset"] == dataset)
                  & (ref_sim["control"] == control)
                  & (ref_sim["est"] == est)]
    rkey = {(int(r.group), int(r.t)): (float(r.att), float(r.se))
            for _, r in grp.iterrows()}

    data = pd.read_csv(os.path.join(SIM_DIR, f"{dataset}.csv"))
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = ATTgt(
            yname="Y", tname="period", idname="id", gname="G", data=data,
            control_group=control, xformla="Y~X",
        ).fit(est_method=est, bstrap=False)

    g = np.asarray(res.MP["group"], dtype=float)
    t = np.asarray(res.MP["t"], dtype=float)
    att = np.asarray(res.results["att"], dtype=float)
    se = np.asarray(res.results["se"], dtype=float)

    n_checked = 0
    for gi, ti, ai, si in zip(g, t, att, se):
        key = (int(gi), int(ti))
        if key not in rkey:
            continue
        ra, rs = rkey[key]
        np.testing.assert_allclose(
            ai, ra, atol=ATT_ATOL,
            err_msg=f"{dataset}/{control}/{est}: ATT g={key[0]} t={key[1]}")
        if np.isfinite(si) and np.isfinite(rs):
            np.testing.assert_allclose(
                si, rs, rtol=SE_RTOL, atol=SE_ATOL,
                err_msg=f"{dataset}/{control}/{est}: SE g={key[0]} t={key[1]}")
        n_checked += 1
    assert n_checked > 0
