"""Parity tests for the parallel-trends Wald pre-test (W / Wpval): csdid vs R `did`.

R `att_gt` reports a Wald pre-test of parallel trends on its `MP` object (`$W`, the
statistic, and `$Wpval`, its chi-square p-value). v0.3.5 adds the same computation to
the port (`ATTgt.MP['W'] / ['Wpval']`). The statistic is a deterministic function of
the analytical influence-function covariance, which the audit has shown matches R to
~1e-10, so this channel is tight.

Reference values in ``r_ref/ref_pretest.csv`` are generated by
``r_ref/generate_reference.R`` against R `did` v2.5.0 (same scenarios as
``test_r_parity.py``). The parity tests skip if the reference CSV is absent (no R).
The guard-semantics tests need no R.
"""
import os
import warnings

import numpy as np
import pandas as pd
import pytest

from csdid.att_gt import ATTgt
from helpers import build_sim_data

REF_DIR = os.path.join(os.path.dirname(__file__), "r_ref")
DATA_DIR = os.path.dirname(__file__)

# scenario -> csdid parameters (mirrors r_ref/generate_reference.R / test_r_parity.py)
SCENARIOS = {
    "mpdta_nev_dr": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~1", control_group="nevertreated",
        est_method="dr"),
    "mpdta_nyt_dr": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~1", control_group="notyettreated",
        est_method="dr"),
    "mpdta_nev_reg_cov": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~lpop", control_group="nevertreated",
        est_method="reg"),
    "mpdta_nev_ipw": dict(
        data="mpdta.csv", yname="lemp", tname="year", idname="countyreal",
        gname="first.treat", xformla="lemp~1", control_group="nevertreated",
        est_method="ipw"),
    "sim_nev_dr": dict(
        data="sim_data.csv", yname="Y", tname="period", idname="id",
        gname="G", xformla="Y~X", control_group="nevertreated", est_method="dr"),
}

# W is a deterministic function of the analytic V (matches R ~1e-10); Wpval is R's
# 5-dp rounded chi-square tail, which the port reproduces exactly.
W_RTOL, W_ATOL = 1e-4, 1e-3
WPVAL_ATOL = 1e-5

_REF_PATH = os.path.join(REF_DIR, "ref_pretest.csv")
_HAS_REF = os.path.exists(_REF_PATH)


def _run(scn):
    p = SCENARIOS[scn]
    df = pd.read_csv(os.path.join(DATA_DIR, p["data"]))
    import contextlib
    import io
    with contextlib.redirect_stdout(io.StringIO()), warnings.catch_warnings():
        warnings.simplefilter("ignore")
        m = ATTgt(yname=p["yname"], tname=p["tname"], idname=p["idname"],
                  gname=p["gname"], data=df, xformla=p["xformla"],
                  control_group=p["control_group"]).fit(
                      est_method=p["est_method"], bstrap=False)
    return m


@pytest.mark.skipif(not _HAS_REF, reason="r_ref/ref_pretest.csv absent (no R)")
@pytest.mark.parametrize("scn", list(SCENARIOS))
def test_pretest_matches_R(scn):
    ref = pd.read_csv(_REF_PATH).set_index("scenario")
    assert scn in ref.index, f"{scn} missing from ref_pretest.csv"
    rW, rWpval = float(ref.loc[scn, "W"]), float(ref.loc[scn, "Wpval"])
    m = _run(scn)
    pW, pWpval = m.MP["W"], m.MP["Wpval"]
    if np.isnan(rW):
        assert pW is None, f"{scn}: R suppressed W but port returned {pW}"
        return
    assert pW is not None, f"{scn}: port returned no W but R has {rW}"
    assert abs(pW - rW) <= W_ATOL + W_RTOL * abs(rW), f"{scn}: W port={pW} R={rW}"
    assert abs(pWpval - rWpval) <= WPVAL_ATOL, f"{scn}: Wpval port={pWpval} R={rWpval}"


# --- guard semantics (no R needed) -----------------------------------------
def _run_sim(df, clustervar=None, bstrap=False):
    import contextlib
    import io
    with contextlib.redirect_stdout(io.StringIO()), warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return ATTgt(yname="Y", tname="period", idname="id", gname="G", data=df,
                     xformla="Y~X", control_group="nevertreated",
                     clustervar=clustervar).fit(est_method="dr", bstrap=bstrap)


def test_pretest_finite_when_pre_cells_exist():
    m = _run_sim(build_sim_data(n=600, time_periods=4, seed=42))
    assert m.MP["W"] is not None and m.MP["W"] > 0
    assert 0.0 <= m.MP["Wpval"] <= 1.0


def test_pretest_none_when_no_pre_cells():
    # demote every treated unit to first-treated in period 2 -> no pre-treatment
    # cell (group > t) survives -> R returns NULL; port returns None.
    df = build_sim_data(n=600, time_periods=4, seed=42)
    df.loc[df["G"] > 0, "G"] = 2
    m = _run_sim(df)
    assert m.MP["W"] is None and m.MP["Wpval"] is None


def test_pretest_suppressed_under_clustered_bootstrap():
    # beyond-unit clustering + clustered bootstrap -> analytic V invalid -> suppress.
    df = build_sim_data(n=600, time_periods=4, seed=42)
    m = _run_sim(df, clustervar="cluster", bstrap=True)
    assert m.MP["W"] is None and m.MP["Wpval"] is None


def test_pretest_computed_under_clustered_analytic():
    # beyond-unit clustering with bstrap=False -> clustered analytical V -> computed.
    df = build_sim_data(n=600, time_periods=4, seed=42)
    m = _run_sim(df, clustervar="cluster", bstrap=False)
    assert m.MP["W"] is not None and m.MP["W"] > 0


def test_pretest_absent_without_inffunc():
    # point-estimates-only mode (compute_inffunc=False): nothing to test on -> None.
    df = build_sim_data(n=600, time_periods=4, seed=42)
    import contextlib
    import io
    with contextlib.redirect_stdout(io.StringIO()), warnings.catch_warnings():
        warnings.simplefilter("ignore")
        m = ATTgt(yname="Y", tname="period", idname="id", gname="G", data=df,
                  xformla="Y~X", control_group="nevertreated",
                  compute_inffunc=False).fit(est_method="dr", bstrap=False)
    assert m.MP["W"] is None and m.MP["Wpval"] is None
